name: Go

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Unittest
      run: |
        go test cf-tool/client
    - name: Build
      run: |
        mkdir -p output
        GOOS=windows GOARCH=amd64 go build -o output/cf_windows_x64 
        GOOS=linux GOARCH=amd64 go build -o output/cf_linux_x64 
        GOOS=darwin GOARCH=amd64 go build -o output/cf_macos_x64 
        GOOS=darwin GOARCH=arm64 go build -o output/cf_macos_arm64 
        ls -al output
    
